### PR TITLE
Update to 1.5.3

### PR DESCRIPTION
**Pull request by chohner**

### CODE REVIEW

**Comment by jakirkham** [comment]
@msarahan, can you please advise us on how to proceed on Windows? It seems untarring the `sdist` is just failing on Python 2.7, but not Python 3.

**Comment by jakirkham** [comment]
cc @humitos @willingc

**Comment by chohner** [comment]
I just tried this on a win8 machine and conda build ran without problems on py27, 34, 35, 36 for both spinx 1.5.3 and 1.5.2 with the conda smithy 2.1.1 update. Any way I can further contribute?

EDIT
To early. the very last build of 1.5.3 (for some reason i left py27 for the very end) crashes with `ValueError: invalid literal for int() with base 10: 'py27'` 

I'll investigate this tomorrow

**Comment by jakirkham** [comment]
Looks like a recent re-rendering PR ( https://github.com/conda-forge/sphinx-feedstock/pull/14 ) failed also. Given how little is changed in that re-rendering PR, I'm thinking this build issue on Windows has nothing to do with this package, but instead some bug in the build chain. Have opened PR ( https://github.com/conda-forge/sphinx-feedstock/pull/15 ), which is literally just an empty commit. Assuming this also fails and you have time @chohner, could you please inspect the versions of packages used in the builds on that PR versus `master`? It would be good to know if we have different versions of `conda`, `conda-build` or other packages.

**Comment by chohner** [comment]
These are the only packages with different versions, with the new ones (failing PR) in ():

```
conda-build-2.1.2 (conda-build-2.1.4)
conda-forge-build-setup-4.3.0 (conda-forge-build-setup-4.4.1)

certifi-2016.9.26 (certifi-2017.1.23)
pyyaml-3.11 (pyyaml-3.12)
jinja2-2.8 (jinja2-2.9.5)
(pycrypto-2.6.1)
```

As it fails inside `conda-build-script.py`, could that be the culprit?

**Comment by jakirkham** [comment]
Raised upstream as issue ( https://github.com/conda/conda-build/issues/1845 ). Please follow along there.

**Comment by jakirkham** [comment]
Thanks for the listing. Sorry, somehow this got buried. My suspicion is something change in `conda-build` with handling paths. Not sure what, but that is helpful information. Could you please cross post this in the issue linked above?

**Comment by jakirkham** [comment]
Thanks for getting this in @chohner.

**Comment by chohner** [comment]
Mh. Circle is now complaining, only for the smithy re-render which worked fine before

```
anaconda_upload is not set.  Not uploading wheels: []
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .....
Using Anaconda API: https://api.anaconda.org
[ERROR] 
Traceback (most recent call last):
  File "/opt/conda/bin/anaconda", line 6, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 87, in main
    description=__doc__, version=version)
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/commands/upload.py", line 244, in main
    args=args))
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/commands/upload.py", line 196, in upload_package
    callback=upload_print_callback(args))
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/__init__.py", line 478, in upload
    self._check_response(res)
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/__init__.py", line 200, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.Conflict: ('file linux-64/sphinx-1.5.3-py27_0.tar.bz2 already exists for package sphinx version 1.5.3', 409)
Traceback (most recent call last):
  File "/opt/conda/bin/upload_or_check_non_existence", line 140, in <module>
    main()
  File "/opt/conda/bin/upload_or_check_non_existence", line 124, in main
    upload(cli, meta, owner, channel)
  File "/opt/conda/bin/upload_or_check_non_existence", line 62, in upload
    env=os.environ)
  File "/opt/conda/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', 'binstar.token', 'upload', '/feedstock_root/build_artefacts/linux-64/sphinx-1.5.3-py27_0.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1

./ci_support/run_docker_build.sh returned exit code 1
```

**Comment by chohner** [comment]
Nevermind, a simple rebuild fixed this

**Comment by jakirkham** [comment]
Seems we have some issues uploading Windows Python 2.7 builds ( https://github.com/conda-forge/sphinx-feedstock/issues/16 ).

**Pull request merged**
