### PR TITLE
NO MRG, TST: Attempt to build `master`

### PR DESCRIPTION
**Pull request by jakirkham**
Please do **not** merge this. The PR here exists for testing purposes only.

Have been running into some issues getting this package to build on Windows in some cases. As the last build passed on `master` and recent re-rendering build failed despite relatively little difference between the two, this commit exists to simply test to see if `master` itself will still build. If not, this implies that something else in the build chain has changed, which is causing this issue. Hopefully comparing this build and the last successful build on `master` will make this obvious what is causing the problem.

### CODE REVIEW

**Comment by jakirkham** [comment]
Raised upstream as issue ( https://github.com/conda/conda-build/issues/1845 ). Please follow along there.

**Comment by jakirkham** [comment]
Toggling to retest.

**Comment by chohner** [comment]
I can confirm that this is now building on my win8 machine and py27! This is also building on appveyor now. probably ok to close this?

**Comment by jakirkham** [comment]
Thanks @chohner. Glad to here and see this is working again.

**Pull request closed without merging**
