### PR TITLE
Upgrade to 1.5.3

### PR DESCRIPTION
**Pull request by humitos**
I change the recipe version to 1.5.3 which is the latest one from pypi: https://pypi.python.org/pypi/Sphinx/1.5.3

This is the first time I do a PR on something related to conda and conda-forge and I'm not sure if this is the correct way. Please, feel free to do any comment/suggestion :)

I'm interested on this new version because of this issue on RTD: https://github.com/rtfd/readthedocs.org/pull/2378

### CODE REVIEW

**Comment by chohner** [comment]
Hi, thanks for the PR! This looks great, although there is actually a PR for 1.5.3 open already: https://github.com/conda-forge/sphinx-feedstock/pull/10

It's unfortunately currently failing on windows py27 (something path related as far as I can tell) and I expect the same here :/ maybe you have some ideas on how to fix this?

**Comment by humitos** [comment]
> Hi, thanks for the PR! This looks great, although there is actually a PR for 1.5.3 open already: #10

Oh, sorry about that. I should have took a look at that first :)

I will close this one to avoid future confusions.

> It's unfortunately currently failing on windows py27 (something path related as far as I can tell) and I expect the same here :/ maybe you have some ideas on how to fix this?

Damn it! It seemed to be so easy to create the new conda-forge version :)

I took a look at the error, but I couldn't realize what's happening. I mean, I also tried to untar the Sphinx file using a Virtualbox with XP and py27 but I didn't have any problem. Could it be related with the appveyor configuration and some strange path with a non-ascii name? (_totally guessing_ :) )

**Comment by chohner** [comment]
Since you have a windows box with py27 running - could you try conda building the recipe?

**Comment by humitos** [comment]
I tried but it's not easy. I had to search for git 1.8.x because winxp doesn't support a newer one, and also had problems with conda instalation and then when trying to create the conda env it worked but it didn't when trying to activate it without any error message. So, I'm not sure how to follow with this. Sorry about that :(

**Comment by chohner** [comment]
Hey no worries, thanks for trying! Maybe someone more involved with conda can help you along - I probably won't have access to a windows machine until next monday :/

**Comment by jakirkham** [comment]
I think it is some Python 2/conda-build issue. I tried to ping Mike, but I think we should just raise an issue upstream with conda-build. Would one of you like to do that?

**Comment by humitos** [comment]
I'm closing this and moving the discussion to #10 to avoid confusions. Sorry about that.

If you get to this PR because whatever reason, please jump to #10 that was the first one to address this issue :grin:

**Comment by jakirkham** [comment]
Raised upstream as issue ( https://github.com/conda/conda-build/issues/1845 ). Please follow along there.

**Pull request closed without merging**
