### PR TITLE
Bump to v7.1.1

### PR DESCRIPTION
**Pull request by AA-Turner**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by AA-Turner** [comment]
@conda-forge-admin, please rerender

**Comment by AA-Turner** [comment]
@conda-forge/core -- builds are failing here and on pypi/warehouse#147 as upper-case versions of URLs don't seem to work with PyPI anymore (see https://github.com/pypi/conveyor/issues/19).

The error in the Azure logs is:

```
RuntimeError: Could not download https://pypi.io/packages/source/S/Sphinx/Sphinx-7.1.1.tar.gz
```

Is there a way to fix this on the conda-forge side, perhaps by lower-casing the download URLs?

A

**Comment by dopplershift** [comment]
The recipe just needs to be updated since those upper cases are hard-coded:
https://github.com/conda-forge/sphinx-feedstock/blob/b3d81bba711ad84ff211fb855d9716b08bc7466e/recipe/meta.yaml#L8

That begs the question of why the PR was even merged when the only build was failing? That's not considered good practice.

**Comment by jakirkham** [comment]
Ryan submitted PR ( https://github.com/conda-forge/sphinx-feedstock/pull/149 ), which fixed the URL. Have merged. It appears packages are up 🚢

That said, agree with double checking CI passed before merging. If it failed, either fixing or asking for help. After all there are lots of folks here who could answer questions 🙂

**Pull request merged**
