### PR TITLE
Add myself as maintainer

### LINKED ISSUE #117: Consider stop using automerge here
Sphinx is a dependency used by a lot of projects in the Python ecosystem, so auto-merging can have a huge negative impact and add more work to other Conda-forge maintainers, when important changes or new dependencies are introduced in future versions.

A recent example is Sphinx 4.4.0, which introduced a new dependency on `importlib-metadata`. This was omitted in https://github.com/conda-forge/sphinx-feedstock/pull/116, which forced other maintainers to step up and submit followup PRs to fix it:

* https://github.com/conda-forge/sphinx-feedstock/pull/116
* https://github.com/conda-forge/admin-requests/pull/378

Pinging @conda-forge/sphinx about this.

### PR DESCRIPTION
**Pull request by ccordoba12**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Add myself as maintainer

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
@chohner, sorry, I didn't see that you're maintaining this feedstock before opening this PR (I assumed you weren't after seeing your comment on issue #117).

However, I can help you and the rest of the team to maintain Sphinx in Conda-forge.

**Comment by chohner** [comment]
Auto-merge was already dropped in 5d4ad53949bf864b4747186b9b4e1ad3c80de7fc so you could remove that change from this PR (just closed the issue)

There are currently three people taking care of this feedstock but of course more wouldn't hurt. @ocefpaf @jakirkham what do you think of replacing @blink1073 with @ccordoba12 ?

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
> Auto-merge was already dropped in https://github.com/conda-forge/sphinx-feedstock/commit/5d4ad53949bf864b4747186b9b4e1ad3c80de7fc so you could remove that change from this PR (just closed the issue)

Ok, that's really good.

> There are currently three people taking care of this feedstock but of course more wouldn't hurt. @ocefpaf @jakirkham what do you think of replacing @blink1073 with @ccordoba12 ?

I'm fine with being maintainer here because Sphinx is very important for us in Spyder. So I changed this PR just to do that.

**Comment by ocefpaf** [comment]
> @ocefpaf @jakirkham what do you think of replacing @blink1073 with @ccordoba12 ?

We should never be replace. One can be removed if they agree on it or if they do it themselves.

**Comment by chohner** [comment]
> > @ocefpaf @jakirkham what do you think of replacing @blink1073 with @ccordoba12 ?
> 
> We should never be replace. One can be removed if they agree on it or if they do it themselves.

Makes sense. Thanks for offering to help @ccordoba12  :)

**Review by chohner — APPROVED** [review]

**Pull request merged**
